name: Package Project

# kiedy mam uruchomic automatyzacje
on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
      # jaki obraz uzyjemy
    steps:
       # pobierz kod z repo
       # moja aplikacja jest w Pythonie wiec dodaj tez pythona!
      #- name: Checkout
      - uses: actions/checkout@v3

      - name: Python3
        uses: actions/setup-python@v3
      # instalacja wymaganych bibliotek
      - name: Install deps
        run: make deps
      # pep-8
      - name: Check PEP-8 style
        run: make lint
      # testy!!!!!
      - name: Run tests
        run: make test

  docker:
    runs-on: ubuntu-latest
    needs: build_and_test
    # needs oznacza, ze wyrzucenie na Dockera nastapi tylko jezel pozytywnie przejdzie builds and tests !!
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: adamosses/test:1.0